networks:
  default:
    external:
      name: webproxy
services:
  gobetween:
    container_name: gobetween.${APP_URL:-mydomain.lan}
    hostname: gobetween.${APP_URL:-mydomain.lan}
    #image: 
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      default: null
    ports:
      - ${BINDIP:-0.0.0.0}:${BINDPORT}:11111
    volumes:
      - ./conf:/conf
      - ${LETSENCRYPT_PATH:-/etc/letsencrypt}:/etc/letsencrypt:ro
version: '3.1'

